openapi: 3.0.0
info:
  title: Lobby Service API
  version: 1.0.0
  description: API documentation for the lobby service
paths:
  /api/resource:
    get:
      summary: Get resource
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string